services:
  backend:
    build: .
    container_name: "backend"
    volumes:
      - .:/app
    depends_on:
      - db
    env_file:
      - .env
    command: "uvicorn main:app --host 0.0.0.0 --port 8000 --reload"

  db:
    image: pgvector/pgvector:pg17
    restart: always
    env_file:
      - .env
    volumes:
      - db_volume:/var/lib/postgresql/data

  odoo:
    image: odoo:19
    restart: always
    depends_on:
      - db
    env_file:
      - .env

    command: odoo -c /etc/odoo/odoo.conf --proxy-mode --db-filter="^%d$$" --no-database-list

  adminer:
    image: adminer
    restart: always

  redis:
    image: redis:8.6.3
    command: redis-server --appendonly yes
    volumes:
      - redis-volume:/data

  worker:
    build: .
    container_name: "worker"
    depends_on:
      - redis
      - db
      - odoo
    command: arq worker.WorkerSettings
    env_file:
      - .env

volumes:
  db_volume:
  n8n-volume:
  odoo-volume:
  redis-volume:
  worker-volume:
