-- Creacion de Schema_Plantilla para nuevos inquilinos
CREATE SCHEMA IF NOT EXISTS "{schema_name}";

-- Creacion Tabla Catalog
CREATE TABLE IF NOT EXISTS "{schema_name}".catalog (
    id_odoo BIGINT PRIMARY KEY, 
    name TEXT NOT NULL,
    description TEXT,
    price NUMERIC(12,2) DEFAULT 0.00,
    stock NUMERIC(12,2) DEFAULT 0.00,
    embedding VECTOR(384),
    conversions JSONB DEFAULT '{{}}'::jsonb, -- Doble llave para escapar JSON en .format() de Python
    metadata JSONB DEFAULT '{{}}'::jsonb
);
                
-- Métrica del Coseno para embeddings
CREATE INDEX IF NOT EXISTS idx_catalog_embedding 
ON "{schema_name}".catalog USING hnsw (embedding vector_cosine_ops);

-- Índice para búsquedas rápidas por nombre
CREATE INDEX IF NOT EXISTS idx_catalog_name ON "{schema_name}".catalog(name);

-- Creacion Tabla Clients
CREATE TABLE IF NOT EXISTS "{schema_name}".clients (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ,
    platform TEXT NOT NULL,
    platform_user_id TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'served' CHECK (status IN ('served','waiting_for_sale','waiting_for_support')),
    channel_id INT,
    metadata JSONB DEFAULT '{{}}'::jsonb,
    partner_id INT NOT NULL,
    CONSTRAINT unique_plataforma_cliente UNIQUE (platform, platform_user_id)
);

CREATE INDEX IF NOT EXISTS idx_clients_name ON "{schema_name}".clients(name);

-- Creacion Tabla Messages
CREATE TABLE IF NOT EXISTS "{schema_name}".messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    platform TEXT NOT NULL,
    platform_user_id TEXT NOT NULL,
    role TEXT NOT NULL DEFAULT 'user' CHECK (role IN ('user','system','assistant','owner')),
    content TEXT NOT NULL,
    ia_is_active BOOLEAN NOT NULL DEFAULT TRUE,
    metadata JSONB DEFAULT '{{}}'::jsonb
);

CREATE INDEX IF NOT EXISTS idx_messages_user_time ON "{schema_name}".messages(platform, platform_user_id, created_at DESC);
